#if !canImport(ObjectiveC)
    import XCTest

    extension HelpCliTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
        // to regenerate.
        static let __allTests__HelpCliTests = [
            ("testHelpCommand", testHelpCommand),
            ("testVersionCommand", testVersionCommand),
        ]
    }

    public func __allTests() -> [XCTestCaseEntry] {
        return [
            testCase(HelpCliTests.__allTests__HelpCliTests),
        ]
    }
#endif
